In [4]:
import pandas as pd 
import numpy as np 


df_resampled_new = pd.read_csv("full_dataset.csv", index_col="timestamp")


# Assuming df_resampled_new is your DataFrame and the index is already a datetime object
df_resampled_new.index = pd.to_datetime(df_resampled_new.index)

# List of periods with start, end, and activity
all_periods = [
    {'start': '2024-07-20 00:00:48', 'end': '2024-07-20 08:00:38', 'activity': '0'},
    {'start': '2024-07-21 00:44:12', 'end': '2024-07-21 09:15:12', 'activity': '0'},
    {'start': '2024-07-22 00:18:02', 'end': '2024-07-22 07:08:09', 'activity': '0'},
    {'start': '2024-07-23 00:15:14', 'end': '2024-07-23 07:09:05', 'activity': '0'},
    {'start': '2024-07-23 20:10:05', 'end': '2024-07-23 23:29:27', 'activity': '0'},
    {'start': '2024-07-24 01:00:04', 'end': '2024-07-24 07:27:24', 'activity': '0'},
    {'start': '2024-07-25 00:46:14', 'end': '2024-07-23 07:11:53', 'activity': '0'},
    {'start': '2024-07-26 00:04:57', 'end': '2024-07-23 09:57:15', 'activity': '0'},
]

# Initialize a new column with default value "1"
df_resampled_new['Awake'] = "1"

# Loop through each period and set activity to "0" for matching timestamps
for period in all_periods:
    start = pd.Timestamp(period['start'])
    end = pd.Timestamp(period['end'])
    activity_value = period['activity']
    
    # Update the 'activity' column for timestamps in the given range
    df_resampled_new.loc[(df_resampled_new.index >= start) & (df_resampled_new.index <= end), 'Awake'] = activity_value

# Print the updated DataFrame
# print(df_resampled_new)
df_resampled_new.to_csv("dataset_no_movement.csv")
df_resampled_new

                     displacement_left  displacement_right Activity Awake
timestamp
2024-07-19 20:00:07         274.070623          256.138172     none     1
2024-07-19 20:00:08         271.232968          257.989736     none     1
2024-07-19 20:00:09         270.861092          256.616547     none     1
2024-07-19 20:00:10         268.845230          255.910090     none     1
2024-07-19 20:00:11         266.708969          256.097339     none     1
...                                ...                 ...      ...   ...
2024-07-27 07:59:57         275.228871          249.422329     none     1
2024-07-27 07:59:58         275.030999          250.134003     none     1
2024-07-27 07:59:59         274.970182          249.699793     none     1
2024-07-27 08:00:00         274.983518          249.809132     none     1
2024-07-27 08:00:01         274.734577          249.646839     none     1

[647995 rows x 4 columns]